data:
  raw: "C:/DATA/Portfolio/python-skeleton-project/data/raw"
  intermediate: "C:/DATA/Portfolio/python-skeleton-project/data/intermediate"
  processed: "C:/DATA/Portfolio/python-skeleton-project/data/processed"
