data:
  raw: "C:/DATA/Portfolio/python-skeleton-prj/data/raw"
  intermediate: "C:/DATA/Portfolio/python-skeleton-prj/data/intermediate"
  processed: "C:/DATA/Portfolio/python-skeleton-prj/data/processed"
